### ISSUE TITLE
Module fails to work when it receives an interaction

### ISSUE THREAD

**Issue by Seniru** [mactul/discord_slash_command#2]
I tried using your library since it looked much simpler than most of the other implementation. But there was this problem when the gateway received a slash interaction.

```
future: <Task finished name='Task-1' coro=<Client.start() done, defined at /workspace/.pip-modules/lib/python3.8/site-packages/discord/client.py:649> exception=TypeError("'guild_id' is an invalid keyword argument for int()")>
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/client.py", line 566, in connect
    await self.ws.poll_event()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/gateway.py", line 509, in received_message
    func(data)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discordslashcommands/manager.py", line 139, in _function_runner
    interaction = Interaction(client=self._client, version=data["version"], type=data["type"], token=data["token"], id=data["id"], guild=guild, channel_id=data["channel_id"], data=data["data"], member_data=data["member"])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discordslashcommands/interactions.py", line 33, in __init__
    self.command = Command(name=data["name"], description=None, client=client, id=int(data["id"], guild_id=guild.id))
TypeError: 'guild_id' is an invalid keyword argument for int()
```

Looks like you forgot to add a `)` after `data["id"]` :P

**Comment by mactul** [comment]
Oh, sorry for the unacceptable bug
It's very strange, you're obviously right, there should be 2 conversions in int
It may be a bug that I added unintentionally while correcting my many spelling mistakes

Thanks for the report, I'll fix it as soon as I get back from holiday
